### PR TITLE
Fix filtering with list of values (not tuple) with PostgreSQL

### PR DESCRIPTION
**Pull request by leplatrem**
@Natim r?

### CODE REVIEW

**Comment by ametaireau** [comment]
Can you provide some more context about why this is needed?

**Comment by Natim** [comment]
```
ProgrammingError("ERREUR:  erreur de syntaxe sur ou pr\xc3\xa8s de \xc2\xab ARRAY \xc2\xbb\nLINE 7:                AND id IN ARRAY['0696366f-be2d-435b-9a50-6688...\n
```

**Comment by Natim** [comment]
Actually it didn't fix the matter:

```
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/cliquet/resource.py", line 383, in collection_get

    include_deleted=include_deleted)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/cliquet/collection.py", line 99, in get_records

    auth=self.auth)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 590, in get_all

    results = cursor.fetchmany(self._max_fetch_size)

  File "/opt/python/2.7.9/lib/python2.7/contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 84, in connect

    raise exceptions.BackendError(original=e)

BackendError: ProgrammingError: syntax error at or near "ARRAY"

LINE 7:                AND id IN ARRAY['f4c8e5ad-cb85-4416-914a-e4cf...
```

**Comment by ametaireau** [comment]
It seems that we miss a test for this.

**Comment by Natim** [comment]
As you can see there is one in the PR, but I will probably add others for the permission backend.

**Comment by ametaireau** [comment]
I've seen this one test and from the code and PR, I couldn't say that a test was missing. But apparently you are getting an error when running Kinto manually, which is a indicator that we are missing a specific test that exercises this behaviour.

Rather than relying on this manual step, it's better to automate it.

**Comment by Natim** [comment]
> Rather than relying on this manual step, it's better to automate it.

Exactly I am trying to find out what would be the best way to reproduce.

**Pull request merged**
