### PR TITLE
Use authn policy name in user prefix

### PR DESCRIPTION
**Pull request by leplatrem**
@Natim r?

### CODE REVIEW

**Comment by Natim** [comment]
If tests are green it works for me :+1: (I am wondering if cliquet-fxa name will change in the process, same for basicauth)

**Comment by leplatrem** [comment]
basicauth does not change.

cliquet-fxa will change indeed, unless we name the policy ``fxaoauth`` in the config file (instead of ``fxa``).
We can add a warning here and in Kinto (but let's be honest, this plugin has no critical use)

**Comment by Natim** [comment]
Ok it works for me.

**Comment by Natim** [comment]
Some test case have to be fixed: https://travis-ci.org/mozilla-services/cliquet/jobs/105195031#L193

**Pull request merged**
