### PR TITLE
Refactor the imports

### PR DESCRIPTION
**Pull request by Natim**
Currently, we import everything from `cliquet.resource`, and it might make more sense to actually import from `cliquet` directly.

e.g.
```python
from cliquet import BaseResource, ResourceSchema, register
```

### CODE REVIEW

**Comment by Natim** [comment]
@hiromipaw it seems to be a little more complicated than I though, actually we have circular imports all over the place if we try to import ``Resource`` in ``__init__.py`` which is mandatory if we want to define it in ``__all__``

I feel like we should probably just keep it the way it is at the moment.

@leplatrem @hiromipaw @ametaireau any thoughts ?

**Comment by hiromipaw** [comment]
I am ok with leaving it like this for now.

**Comment by leplatrem** [comment]
This is a very high priority.

I feel embarrassed about the efforts Sylvia provided on this though...

**Comment by hiromipaw** [comment]
@leplatrem it's ok I learned a lot and I can always take another issue from the stack :)

**Comment by leplatrem** [comment]
Well, I am truely sorry, I sincerely hope your next experience will be even more positive (ie. «merged») :)

Thanks again! 

Closing :(

**Pull request closed without merging**
