### PR TITLE
Allow-Control-Expose-Headers headers is missing on 400 errors.

### PR DESCRIPTION
**Pull request by Natim**
Refs: https://github.com/Kinto/kinto.js/issues/110

### CODE REVIEW

**Comment by ametaireau** [comment]
That's an implementation limitation in Cornice. We might want to document it.

This PR looks okay to me. I'm not sure about the location of the import, but it looks good to me otherwise.

**Comment by Natim** [comment]
>  I'm not sure about the location of the import

This is because cliquet import utils which import Service :(

**Comment by Natim** [comment]
Maybe should I put it on line 174?

**Comment by ametaireau** [comment]
Ah okay. Might be a solution then yes.

**Pull request merged**
