### PR TITLE
Change arrow direction in logo

### PR DESCRIPTION
**Pull request by leplatrem**
As suggested by @Natim

### CODE REVIEW

**Comment by ametaireau** [comment]
I actually find this weird :) What does the arrow mean? Is it a force? Here if the ratchet goes to this direction, then the wheel can go two directions, which is what we don't want.

**Comment by leplatrem** [comment]
I think I know the solution : make it both ways!

**Comment by Natim** [comment]
Yes I like it :)

**Comment by Natim** [comment]
On devrait l'afficher dans le README aussi.

**Pull request merged**
