### PR TITLE
Rename BaseResource and ProtectedResource (fixes #439)

### LINKED ISSUE #439: Rename BaseResource and ProtectedResource ?
Currently : 

* BaseResource isolates records by user
* ProtectedResource adds permissions management via ``"permissions"`` attribute in payloads

I propose that we rename them:

*  ``UserResource``, whose records are isolated by user
* ``PermissionResource`` ? ``SharableResource`` ? ``ProtectedResource`` ?
* Add ``GlobalResource``, whose records are the same for any user

Any thoughts ?

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by Natim** [comment]
This is what I call a refactor :+1: I like the Deprecation system youǘe added.

**Comment by leplatrem** [comment]
rebased.

Thanks for the positive feedback :)

**Comment by leplatrem** [comment]
@almet, since this is a major renaming, I'd like a r? from you please :)

**Comment by almet** [comment]
Neat! That looks good to me. +1 for the deprecation mechanism and the renaming. Thanks.

**Pull request merged**
