### PR TITLE
Change the reference title.

### PR DESCRIPTION
**Pull request by Natim**
I'd like to change the Reference title that doesn't help too much.

Also I'm not sure how to name it.

Since we have API endpoint, I was thinking about
 - Advanced documentation
 - Python API
 - Cliquet guts

### CODE REVIEW

**Comment by leplatrem** [comment]
+1

I propose we also rename *API* to *Protocol*

**Comment by Natim** [comment]
Updated.

**Comment by leplatrem** [comment]
Oh! You changed to guts ? Do you have an example of a library using «guts» instead of *reference* ? 

Also, we mentioned the ``/api/`` in many places (like in Kinto docs). Should we provide a redirection using some kind of sphinx plugin ?

**Comment by Natim** [comment]
> Do you have an example of a library using «guts» instead of reference ? 

Nor guts nor reference actually, I can revert to reference if you'd like.

> Also, we mentioned the /api/ in many places (like in Kinto docs). Should we provide a redirection using some kind of sphinx plugin ?

We can also keep the filename and just change the TOC what do you think?

**Comment by tarekziade** [comment]
Guts sounds like frenglish. Internals ?

Also if protocol refers to the HTTP protocol, I'd be explicit

**Comment by Natim** [comment]
I like ``Internals``

**Comment by leplatrem** [comment]
+1 for *Internals* and *HTTP Protocol*

**Comment by ametaireau** [comment]
> +1 for Internals and HTTP Protocol

For me as well :)

**Comment by Natim** [comment]
Updated.

**Pull request merged**
