### PR TITLE
Fix typo in project name

### PR DESCRIPTION
**Pull request by brouberol**

### CODE REVIEW

**Comment by Natim** [comment]
It was Cliquet before after we changed it to Pyramid, now it is Cornice, I am a bit lost. @leplatrem any thoughts ?

**Comment by brouberol** [comment]
I think it was supposed to be Cliquet instead of Pyramid, and I put
Cornice by mistake. I'm pretty confused too now.

--
B
 
 
On Sun, Jun 21, 2015, at 12:53 PM, Rémy HUBSCHER wrote:
> It was Cliquet before after we changed it to Pyramid, now it is Cornice, I am a bit lost. @leplatrem[1] any thoughts ?


> —
> Reply to this email directly or view it on GitHub[2]. 


>  
 


Links:

  1. https://github.com/leplatrem
  2. https://github.com/mozilla-services/cliquet/pull/333#issuecomment-113884759

**Comment by ametaireau** [comment]
It is supposed to be "cliquet".

**Comment by ametaireau** [comment]
Thanks ;)

**Pull request merged**
