### PR TITLE
Fix crash when type of value in exclude/include is wrong (fixes Kinto/kinto#587)

### PR DESCRIPTION
**Pull request by leplatrem**
@Natim r?

### CODE REVIEW

**Comment by glasserc** [comment]
Isn't this silent failure? I almost prefer the original behavior..

**Comment by Natim** [comment]
Yes why not doing a cast to the correct type in that case?

**Comment by leplatrem** [comment]
> Isn't this silent failure? I almost prefer the original behavior..

You're right, we shall return a 400. I'll rework the patch.

**Comment by Natim** [comment]
Would you add a test to make sure the description of the error is the one you are looking for?

**Comment by Natim** [comment]
It looks good to me

**Pull request merged**
