### PR TITLE
Fix ujson escaping (fixes #131)

### LINKED ISSUE #131: usjon escape issue
As seen in https://github.com/mozilla-services/readinglist/issues/205 we have issues with URLs.

https://github.com/esnme/ultrajson/issues/110

I am going to remove ujson for the time being, but a better long term solution might be to sanity check the escaped / before the queries are done.

### PR DESCRIPTION
**Pull request by leplatrem**
fixes #131

### CODE REVIEW

**Comment by leplatrem** [comment]
@ametaireau @tarekziade r?

**Comment by ametaireau** [comment]
LGTM, waiting on travis

**Comment by leplatrem** [comment]
@ametaireau @Natim  updated with new fixes regarding backslashes and CloudStorage

**Comment by leplatrem** [comment]
Tests failed because of https://github.com/esnme/ultrajson/issues/165

Now pass \o/

**Pull request merged**
